config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # namespace :admin do
  #   resources :reviews
  #   resources :movies
  #   resources :users
  # end

  resources :movies

  resources :movies do
    resources :reviews, controller: 'movie_reviews'
  end

  resources :reviews, only: [:index, :new, :create, :show]
  resources :users
  resources :sessions, only: [:new]
  get '/login', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get 'top_movies' => 'movies#top_movies'
  root 'movies#index'

  get 'users/:id/user_data', to: 'users#user_data'
  get 'movies/:id/movie_data', to: 'movies#movie_data'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  helper_method :params

  def index
    if session[:user_id]
      @user = current_user
    end
    @movies = Movie.order(:title)
    @reviews = Review.last(5).reverse
  end

  def show
    @movie = Movie.find(params[:id])
  end

  # def update
  #   @movie = Movie.find(params[:id])
  #   @movie.update(params[:movie][:reviews])
  # end

  def top_movies
    @movies = Movie.top_movies
    render 'top_movies.html.erb'
  end

  def movie_data
    movie = Movie.find(params[:id])
    render json: movie, serializer: MovieSerializer, status: 200
  end

private

  def movies_params
    params.require(:movie).permit(:reviews, :title, :content)
  end


end

app/views/movies/_movie_lists.html.erb
<h1>This movie has the most reviews!</h1>

<% Movie.most_reviews.map do |movie| %>
<h3><%= link_to movie.title, movie_reviews_path(movie)  %></h3>
<% end %>

app/views/movies/index.html.erb
<% if session[:user_id] %>
  <h1><%= @user.name %></h1>
  Hello, <%= @user.name %>. <%= link_to "Click here to review a movie", new_review_path %>.
  <p><%= link_to 'Logout', logout_path %></p>
<% else %>
  <p><%= link_to 'click here to login', '/login' %></p>
  <p><%= link_to "create new user", new_user_path %></p>
  <p><%= link_to('Log in with Facebook!', '/auth/facebook') %></p>
<% end %>

<h1>Our Most Recent Movie Reviews!</h1>


<div>
  <ul>
    <% @reviews.each do |review| %>
      <li>
        <h4><%= review.movie.title %></h4>
      </li>
      <li>
        Review: <%= link_to review.title, movie_review_path(review.movie.id, review.id) %>

      <% end %>
      </li>
  </ul>
</div>

<div>
  <h3>View our movies with the highest average rating!</h3>
  <%= link_to 'view highest rated movies', action: "top_movies" %>


<div>
  <h3>Filter by Movie:</h3>
  <%= form_tag("/movies", method: "get") do %>
    <%= select_tag "title", options_from_collection_for_select(Movie.all, "title", "title"), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>


<!-- Filter By Movie Title -->
<% if !params[:title].blank? %>
  <% @movies_by_title = Movie.where(title: params[:title]) %>
<% end %>

<% if @movies_by_title %>
  <% @movies_by_title.each do |movie| %>
    <h4><%= movie.title %></h4>
      <ul>
        <% movie.reviews.each do |review| %>
          <li>
            Review Title: <%= review.title %>
          </li>
          <li>
            Review Content: <%= review.content %>
          </li>
        <% end %>
    </ul>
  <% end %>
<% end %>
<!-- end filter movie by title -->

<h2>See the movies with the most reviews!</h2>
<%= render 'movie_lists' %>

app/views/movies/show.html.erb
Here is your selected movie!

<h1><%= @movie.title %></h1>

<ul>

    <li>
      <h4>Review Title: </h4> <%= @review.title %>
      <h4>Review Content: </h4><%= @review.content %>
      <h4>Review Rating: </h4><%= @review.rating %>
      <p>Author: <%= link_to @review.user.name, user_path(@review.user) %></p>
    </li>


</ul>

<button class="js-reviews" data-id="<%= @movie.id %>">See All Reviews...</button>
<button class="js-topReviews" data-id="<%= @movie.id %>">See Top Reviews...</button>

<div id="body-<%= @movie.id %>"></div>

app/views/movies/top_movies.html.erb
<h1>Here are the movies with the highest average rating!</h1>

<ul>
  <% @movies.each do |movie| %>
  <li>
    <%= link_to movie.title, movie_reviews_path(movie.id) %>
    Average Rating: <%= average_rating(movie) %>

  </li>
  <% end %>
</ul>